config:
  partial_parse: true
jaffle_shop:
  outputs:
    ci:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: public
      threads: 16
      type: snowflake
      user: GITHUB
      warehouse: COMPUTE_WH
  target: ci
