name: Cleanup DBT
on:
  pull_request:
    types: [closed]

env:
  DBT_PROJECT: jaffle_shop

jobs:

  Build:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      DBT_PROFILES_DIR: .

    defaults:
      run:
        working-directory: transformation/dbt/${{ env.DBT_PROJECT }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: "3.9.x"

      - name: Install DBT
        run: |
          pip install dbt-core==1.0.1 dbt-snowflake

      - name: Cache DBT Dependencies
        id: cache-dbt-deps
        uses: actions/cache@v2
        with:
          path: transformation/dbt/${{ env.DBT_PROJECT }}/dbt_packages/
          key: ${{ env.DBT_VERSION }}-dbt-deps-${{ hashFiles('**/${{ env.DBT_PROJECT }}/packages.yml') }}

      - name: Install DBT Packages
        if: steps.cache-dbt-deps.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo ${{ env.SNOWFLAKE_ACCOUNT }}
          echo ${{ env.SNOWFLAKE_DATABASE }}
          dbt deps --target ci

      - name: Get Branch Name (Pull Request)
        if: github.event_name == 'pull_request' && endsWith(github.ref, '/main') != true
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Set $SNOWFLAKE_DATABASE to an Ephemeral Database
        if: "!endsWith(github.ref, '/main')"
        run: |
          echo "SNOWFLAKE_DATABASE=CI_$(python ../utils/get_suffix.py --branch ${{ env.BRANCH_NAME }} )" >> $GITHUB_ENV

      - name: Drop Ephemeral Database
        run: |
          dbt run-operation drop_database --args '{database: ${{ env.SNOWFLAKE_DATABASE }} }'
        if: (github.event.action == 'closed' || github.event.pull_request.merged == true)
